### ISSUE TITLE
Rendering bugs

### ISSUE THREAD

**Issue by R-Ceph** [jidiai/Competition_Olympics-Running#2]
When using render mode under Linux, the game window will appear and disappear repeatedly.
Testing on Ubuntu 18.04

**Comment by YanSong97** [comment]
now should be fixed, many thanks ! 👍

**Comment by R-Ceph** [comment]
Thanks for your reply, but I found that the new code has some problems when using multi-process. I think possible solutions should be:
1. "Pygame.display.set_mode(self.WIN_SIZE)" should not appear in the initialization of the Viewer class, otherwise, a multi-process error will occur:

> XIO: fatal IO error 11 (Resource temporarily unavailable) on X server ":0" after 235 requests (235 known processed) with 0 events remaining

2.  "pygame.display.set_mode(self.WIN_SIZE)" should now be used when calling render(), otherwise the game window will appear and disappear repeatedly.
